<?php

namespace Thomas\Bundle;

use Illuminate\Support\ServiceProvider;

class ThomasBundleServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/views','thomas');
        $this->loadMigrationsFrom(__DIR__.'/database/migrations');

        $this->mergeConfigFrom( __DIR__.'/config/thomas.php' ,'thomas');

        $this->publishes([
            __DIR__.'/config/thomas.php'=>config_path('thomas.php'),
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
