<?php

namespace Thomas\Bundle;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;
use Thomas\Bundle\Models\Admin;

class ThomasBundleServiceProvider extends ServiceProvider
{
    public function boot()
    {

        $this->SetWhereLike();
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->loadViewsFrom(__DIR__ . '/views', 'thomas');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');

        $this->mergeConfigFrom(__DIR__ . '/config/thomas.php', 'thomas');
//        $this->mergeConfigFrom(__DIR__ . '/config/auth.php', 'auth');

        $this->publishes([
            __DIR__ . '/config/thomas.php' => config_path('thomas.php'),
        ]);

        $this->publishes([
            __DIR__ . '/Models/' => base_path('app/Http/Thomas/Models')
        ], 'Models');

    }

    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
        config([
            'auth.guards.admin' => [
                'driver' => 'session',
                'provider' => 'admins',
            ],
            'auth.guards.admin_api' => [
                'driver' => 'token',
                'provider' => 'admins',
                'hash' => false,
            ],
            'auth.guards.sanctum_admin' => [
                'driver' => 'sanctum',
                'provider' => 'admins',
            ],
            'auth.providers.admins' => [
                'driver' => 'eloquent',
                'model' => Admin::class
            ],
            'auth.passwords.admins' => [
                'provider' => 'admins',
                'table' => 'password_resets',
                'expire' => 60,
                'throttle' => 60,
            ]
        ]);
    }

    private function SetWhereLike()
    {
        Builder::macro('whereLike', function ($attributes, string $searchTerm) {
            $this->where(function (Builder $query) use ($attributes, $searchTerm) {
                foreach (\Arr::wrap($attributes) as $attribute) {
                    $query->when(
                        \Str::contains($attribute, '.'),
                        function (Builder $query) use ($attribute, $searchTerm) {
                            [$relationName, $relationAttribute] = explode('.', $attribute);

                            $query->orWhereHas($relationName, function (Builder $query) use ($relationAttribute, $searchTerm) {
                                $query->where($relationAttribute, 'LIKE', "%%" . strtolower($searchTerm) . "%%");
                            });
                        },
                        function (Builder $query) use ($attribute, $searchTerm) {
                            $query->orWhere($attribute, 'LIKE', "%{$searchTerm}%");
                        }
                    );
                }
            });

            return $this;
        });
    }
}
