<?php

namespace Thomas\Bundle;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\ServiceProvider;

class ThomasBundleServiceProvider extends ServiceProvider
{
    public function boot()
    {

        $this->SetWhereLike();
        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');
        $this->loadViewsFrom(__DIR__ . '/views', 'thomas');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');

        $this->mergeConfigFrom(__DIR__ . '/config/thomas.php', 'thomas');

        $this->publishes([
            __DIR__ . '/config/thomas.php' => config_path('thomas.php'),
        ]);

        $this->publishes([
            __DIR__.'/Models/' => base_path('app/Http/Models')
        ], 'Models');

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    private function SetWhereLike(){
        Builder::macro('whereLike', function ($attributes, string $searchTerm) {
            $this->where(function (Builder $query) use ($attributes, $searchTerm) {
                foreach (\Arr::wrap($attributes) as $attribute) {
                    $query->when(
                        \Str::contains($attribute, '.'),
                        function (Builder $query) use ($attribute, $searchTerm) {
                            [$relationName, $relationAttribute] = explode('.', $attribute);

                            $query->orWhereHas($relationName, function (Builder $query) use ($relationAttribute, $searchTerm) {
                                $query->where($relationAttribute, 'LIKE', "%%".strtolower($searchTerm)."%%");
                            });
                        },
                        function (Builder $query) use ($attribute, $searchTerm) {
                            $query->orWhere($attribute, 'LIKE', "%{$searchTerm}%");
                        }
                    );
                }
            });

            return $this;
        });
    }
}
